### ISSUE TITLE
Failed to extract any files

### ISSUE THREAD

**Issue by LamZykoss** [Tectors/Wickend-js#1]
When I'm trying to extract files (correct path to pak files and dll in the code folder) It says "File error: The system cannot find the specified file"
![image](https://user-images.githubusercontent.com/74079755/113187920-cb7cbd00-922f-11eb-999e-1d1f2aa8e033.png)
![image](https://user-images.githubusercontent.com/74079755/113187933-d1729e00-922f-11eb-8006-4bea8f31ede5.png)

**Comment by Tectors** [comment]
This is odd, I'll respond after checking.

**Comment by Tectors** [comment]
Could you show the whole directory.

**Comment by LamZykoss** [comment]
![image](https://user-images.githubusercontent.com/74079755/113656210-611daf80-9669-11eb-8da0-4b9756a0dd2d.png)

**Comment by Tectors** [comment]
The paks folder isn't there, it only needs the global files from your game.

**Comment by Tectors** [comment]
Has this issue been resolved?

**Comment by Tectors** [comment]
Fixed in dms.
